### PR TITLE
Update warnings for minimatch and gulp-util

### PR DESCRIPTION
**Pull request by rejas**
Fixes warnings from installing your plugin due to next gulp version and deprecation of gulp-util. 
Also updates minimatch (regexp dos issue) and other cleanups

### CODE REVIEW

**Comment by rejas** [comment]
Hi @sirlantis you need help maintaining this repo or how can I help getting this change into the code?

**Comment by sirlantis** [comment]
Hey @rejas - thanks for the contribution!

I'm indeed not actively maintaining this repo anymore, but will try this weekend to get this change in.

**Comment by rejas** [comment]
Thx for the invite. Maybe moving this plugin to https://github.com/gulp-community would be an option? 
@phated @demurgos : thoughts about this plugin?

**Comment by sirlantis** [comment]
@rejas If that's an option, certainly willing to do so.

**Comment by rejas** [comment]
@sirlantis no response yet from @demurgos regarding the gulp-community move. maybe transfering it to me for now especially the npm rights would be an option?

**Comment by demurgos** [comment]
Gulp-community discussion: https://github.com/gulp-community/meta/issues/1#issuecomment-399016804

**Comment by rejas** [comment]
so, what do you say @sirlantis? ready to move the repo?

**Comment by demurgos** [comment]
Add me as a contributor to this repo and I'll do the transfer if it's OK for you.

**Comment by rejas** [comment]
I havent got the right but I hope @sirlantis reads this :-)

**Pull request merged**
